### ISSUE TITLE
Construire l'environnement de simulation ROS

### ISSUE THREAD

**Issue by Chrispako990210** [Beam-create/S4H2022-RufUS#32]

**Comment by simj5121** [comment]
Nb d'heures : (Sem. 24-28 janv 12 heures),
Risques : 
-Intégration des CAD
-Frottement entre les joints
Problèmes :

**Comment by simj5121** [comment]
L'environnement global est terminer : 
-Possible de faire bouger de manière indépendante chaque joint d'un robot simple à 3 axes
